import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { listProviderDefinitions } from "../src/config.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const definitions = listProviderDefinitions();
const verification = JSON.parse(readFileSync(resolve(root, "config/verification.json"), "utf8"));

const envLines = [
  "# Generated by npm run provider:docs. Do not edit provider entries manually.",
  "# Set only the keys for providers you use.",
  ""
];
for (const item of definitions) {
  envLines.push(`${item.credentials.envKeys[0]}=`);
  if (item.credentials.envKeys.length > 1) {
    envLines.push(`# Alternative keys: ${item.credentials.envKeys.slice(1).join(", ")}`);
  }
}
envLines.push("", "# Optional per-provider overrides.");
for (const item of definitions) {
  const prefix = item.id.toUpperCase().replaceAll("-", "_");
  envLines.push(`# ${prefix}_MODEL=${item.model}`);
  envLines.push(`# ${prefix}_BASE_URL=${item.endpoint.baseUrl}`);
}
writeFileSync(resolve(root, ".env.example"), `${envLines.join("\n")}\n`);

const statusLabel = {
  verified: "已真实验证",
  pending: "待真实验证",
  blocked: "受外部状态阻塞",
  failed: "验证失败"
};
const rows = definitions.map((item) => {
  const state = verification[item.id] || { status: "pending", notes: "尚未记录联调状态" };
  const capabilities = Object.entries(item.capabilities).filter(([, enabled]) => enabled).map(([name]) => name).join(", ");
  const profiles = item.modelProfiles ? Object.keys(item.modelProfiles).map((model) => `\`${model}\``).join(" / ") : `\`${item.model}\``;
  return `| \`${item.id}\` | \`${item.model}\` | ${profiles} | ${item.name} | ${capabilities || "-"} | ${statusLabel[state.status] || state.status} | ${state.notes || "-"} |`;
});
const catalog = [
  "# Provider Catalog",
  "",
  "> 此文件由 `npm run provider:docs` 从 `config/providers/*.json` 和 `config/verification.json` 生成，请勿手工维护表格。",
  "",
  "| Provider | 默认模型 | 可选 Model Profiles | 名称 | 能力 | 联调状态 | 备注 |",
  "| --- | --- | --- | --- | --- | --- | --- |",
  ...rows,
  "",
  "## 配置规则",
  "",
  "- 新增或修改兼容模型时，只修改对应的 `config/providers/<id>.json`。",
  "- 一个 Provider 包含多种参数契约时，在 `modelProfiles` 中逐个声明；环境变量只能选择已声明模型。",
  "- 真实联调完成后，只更新 `config/verification.json`。",
  "- 运行 `npm run provider:validate` 校验配置，运行 `npm run provider:docs` 重新生成本文件和 `.env.example`。",
  "- API Key 只保存在 `.env`，不得写入 Provider 配置或联调状态。",
  ""
].join("\n");
writeFileSync(resolve(root, "PROVIDER_CATALOG.md"), catalog);

console.log(JSON.stringify({ ok: true, generated: [".env.example", "PROVIDER_CATALOG.md"] }, null, 2));
